site_name: Repo-Template
docs_dir: docs
site_description: Repository Template
repo_url: https://github.com/EcoSphereNetwork/Repo-Template
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - include:
      path: docs/templates
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true
  - git-revision-date-localized


nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Development:
    - Contributing: development/contributing.md
    - CI/CD: development/cicd.md
  - Templates:
    - Issue Template: templates/issue_template.md
    - Bug Report: templates/bug_report.md
    - Documentation Update: templates/documentation_update.md
    - Feature Request: templates/feature_request.md
    - Pull Request Template: templates/pull_request_template.md
  - Guides: 
    - Github Discord Webhook: guides/github-discord-webhook/github-discord-webhook.md