site_name: EcoSphere Project Template
site_description: Documentation for EcoSphere Project Template
repo_url: https://github.com/EcoSphereNetwork/Repo-Template_-new-
repo_name: EcoSphereNetwork/Repo-Template

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Advanced Features: user-guide/advanced-features.md
  - Development:
    - Contributing: development/contributing.md
    - Code Style: development/code-style.md
    - Testing: development/testing.md
  - API Reference:
    - Core API: api/core.md
    - Utilities: api/utils.md
  - About:
    - Release Notes: about/changelog.md
    - License: about/license.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
          selection:
            members: true
          rendering:
            show_source: true
            show_if_no_docstring: true